# Generated by Django 5.0.2 on 2024-02-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks1', '0002_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TodoList',
        ),
    ]
